swagger: '2.0'
info:
  title: TeslaMonitor API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /global_sentiments:
    get:
      tags: [Sentiment, NLP, "Social Networks"]
      operationId: app.get_historic_global_sentiments
      summary: Get all recent global sentiments
      parameters:
        - name: from_ms_ago
          description: Minimum Unix epoch/timestamp in milliseconds (UTC) of the items returned (when they were computed).
          in: query
          type: integer
          format: int64
          minimum: 0
          maximum: 100000000000
          default: 86400000
        - name: from_created_epoch_ms
          description: Minimum Unix epoch/timestamp in milliseconds (UTC) of the items returned (when they were computed).
          in: query
          type: integer
          format: int64
          default: 1532441907000
          minimum: 1532441907000
        - name: limit
          description: Max number of items returned
          in: query
          type: integer
          format: int32
          minimum: 0
          maximum: 250000
          default: 1000
        - name: sample_rate
          description: Value lower than 1.0 useful when trying to cover a long period, but trying to preserve some bandwith (like with dashboards).
          in: query
          type: number
          format: float
          minimum: 0.01
          maximum: 1.0
          default: 1.0
        - name: sentiment_type
          in: query
          type: string
          default: all
          enum:
              - all
              - social_teslamonitor
              - social_external_ensemble
              - news_external_ensemble
              - global_external_ensemble
      responses:
        200:
          description: Return recent global sentiments
          schema:
            type: array
            items:
              $ref: '#/definitions/GlobalSentiment'


definitions:
  GlobalSentiment:
    type: object

    properties:
      sentiment_type:
        type: string
        description: Type of sentiment social/news and source external_computations (Benzinga, Tipranks, ...)/teslamonitor
        example: "social_teslamonitor"
        readOnly: true
      sentiment_seconds_back:
        type: integer
        format: int32
        description: How many seconds for past sentiment were taken into account to calculate this data point
        example: 43200
        readOnly: true
      created_at_epoch_ms:
        type: integer
        format: int64
        description: When the sentiment value was computed
        minimum: 1532441907000
        example: 1533441907000
        readOnly: true
      sentiment_absolute:
        type: number
        format: float
        description: Sentiment value (can be bigger than 100)
        example: 102.5
        readOnly: true
      sentiment_normalized:
        type: number
        format: float
        description: Sentiment normalised value
        minimum: 0
        maximum: 1.0
        example: 0.25
        readOnly: true